#Testes da tabela bairros

### Listar dados
GET http://localhost:4167/bairros

### Mostrar campo por id
GET http://localhost:4167/bairros/2

### Inserir novo dado
POST http://localhost:4167/bairros
Content-Type: application/json

{
    "bairro": "Nova Cidade",
    "fk_idcidade": 1
}

### Inserir um dado com base no id
PUT http://localhost:4167/bairros/1
Content-Type: application/json

{
    "bairro": "Novo Mundo",
    "fk_idcidade": 1
}

### Excluir um dado com base no id
DELETE http://localhost:4167/bairros/2