
###
POST http://localhost:6789/login
Content-Type: application/json

{
  "email": "testeemial@email.com",
  "senha": "Teste1234."
}

###
POST http://localhost:6789/login/ong
Content-Type: application/json

{
  "email": "testeong12@email.com",
  "senha": "Teste1234."
}
