#Testes da tabela ongs

### Listar dados
GET http://localhost:6789/ongs

### Mostrar campo por id
GET http://localhost:6789/ongs/2

### Inserir novo dado
POST http://localhost:6789/ongs
Content-Type: application/json

{
    "nome": "Ong teste 2",
    "cnpj": 222222222,
    "telefone": 22222222,
    "descricao": "Descrição teste ong teste 2.",
    "fk_idendereco": 1,
    "comp_estatuto": "Comprovante teste.",
    "comp_cnpj": "Comprovante teste.",
    "email": "ongteste2@gmail.com",
    "senha": "12345",
    "fk_idtipo": 4
}

### Inserir um dado com base no id
PUT http://localhost:6789/ongs/2
Content-Type: application/json

{
    "nome": "Ong teste 1",
    "telefone": 1111111,
    "descricao": "Descrição.",
    "fk_idendereco": 1,
    "email": "ongteste4@gmail.com",
    "senha": "12345",
    "foto": "teste foto.",
    "banner": "teste banner."
}

### Excluir um dado com base no id
DELETE http://localhost:6789/ongs/2