#Testes da tabela ongsfavoritadas

### Listar dados
GET http://localhost:4167/ongsfavoritadas

### Mostrar campo por id
GET http://localhost:4167/ongsfavoritadas/2

### Inserir novo dado
POST http://localhost:4167/ongsfavoritadas
Content-Type: application/json

{
    "fk_idusuario": 1,
    "fk_idong": 1
}

### Inserir um dado com base no id
PUT http://localhost:4167/ongsfavoritadas/2
Content-Type: application/json

{
    "fk_idusuario": 6,
    "fk_idong": 1
}

### Excluir um dado com base no id
DELETE http://localhost:4167/ongsfavoritadas/2