#Testes da tabela portespet

### Listar dados
GET http://localhost:3600/portespets

### Mostrar campo por id
GET http://localhost:3600/portespets/3

### Inserir novo dado
POST http://localhost:3600/portespets
Content-Type: application/json

{
    "porte": "tgarg"
}

### Inserir um dado com base no id
PUT http://localhost:3600/portespets/2
Content-Type: application/json

{
    "porte": "Grande"
}

### Excluir um dado com base no id
DELETE http://localhost:3600/portespets/3