#Testes da tabela racaspet

### Listar dados
GET http://localhost:4167/racaspets

### Mostrar campo por id
GET http://localhost:4167/racaspets/2

### Inserir novo dado
POST http://localhost:4167/racaspets
Content-Type: application/json

{
    "raca": "fefaef",
    "fk_idespeciepet": 1
}

### Inserir um dado com base no id
PUT http://localhost:4167/racaspets/3
Content-Type: application/json

{
    "raca": "adned",
    "fk_idespeciepet": 1
}

### Excluir um dado com base no id
DELETE http://localhost:4167/racaspets/3