#Testes da tabela usuarios

### Listar dados
GET http://localhost:6789/usuarios

### Mostrar campo por id
GET http://localhost:6789/usuarios/3

### Inserir novo dado
POST http://localhost:6789/usuarios
Content-Type: application/json

{
    "nome": "Maria Fernanda da Silva",
    "email": "mfsferandaslva794@gmail.com",
    "telefone": "(16)99393-6341",
    "fk_idsexo": 1,
    "data_nasc": "29/05/2006",
    "cpf": "111.111.110-11",
    "senha": "testinhosenha",
    "foto": "testinhofoto",
    "fk_idendereco": 1,
    "fk_idtipo": 1
}

### Inserir um dado com base no id
PUT http://localhost:6789/usuarios/1
Content-Type: application/json

{
    "nome": "Maria Fernanda Silva",
    "telefone": "(16)99393-6344",
    "fk_idsexo": 1,
    "senha": "testinhosenhona",
    "foto": "sem foto",
    "fk_idendereco": 1,
    "fk_idtipo": 1
}

### Excluir um dado com base no id
DELETE http://localhost:6789/usuarios/5