### Lista bairros
GET http://localhost:4501/bairros

### Encontra bairro pelo ID
GET http://localhost:4501/bairros/3

### Adicionar bairro
POST http://localhost:4501/bairros
Content-Type: application/json

{
  "nome": "Jardim",
  "cidade_id": 1
}

### Deleta bairro pelo ID
DELETE http://localhost:4501/bairros/3

### Altera bairro pelo ID
PUT http://localhost:4501/bairros/5
Content-Type: application/json

{
  "nome": "Jardim",
  "cidade_id": 3
}