### Lista bairros
GET http://localhost:4501/bairros

### Encontra bairro pelo ID
GET http://localhost:4501/bairros/18

### Adicionar bairro
POST http://localhost:4501/bairros
Content-Type: application/json

{
  "bairro": "Teste",
  "id_cidade_fk": 2
}

### Deleta bairro pelo ID
DELETE http://localhost:4501/bairros/20


### Altera bairro pelo ID
PUT http://localhost:4501/bairros/18
Content-Type: application/json

{
  "bairro": "Bairro alto",
  "id_cidade_fk": 1
}