### Lista cidades
GET http://localhost:4501/cidades

### Encontra cidade pelo ID
GET http://localhost:4501/cidades/8

### Adicionar cidade
POST http://localhost:4501/cidades
Content-Type: application/json

{
  "cidade": "Taquaritinga",
  "id_uf_fk": 25
}

### Deleta cidade pelo ID
DELETE http://localhost:4501/cidades/8

### Altera cidade pelo ID
PUT http://localhost:4501/cidades/8
Content-Type: application/json

{
  "cidade": "Alagoinha",
  "id_uf_fk": 25
}
