### Lista enderecos

GET http://localhost:4501/enderecos

### Encontra endereco pelo ID

GET http://localhost:4501/enderecos/3

### Adicionar endereco

POST http://localhost:4501/enderecos
Content-Type: application/json

{
    "id_uf_fk": 25,
    "id_cidade_fk": 2,
    "id_bairro_fk": 13,
    "id_rua_fk": 1,
    "numero": 1650,
    "cep": 15997070
}

### Deleta endereco pelo ID

DELETE http://localhost:4501/enderecos/3

### Altera endereco pelo ID

PUT http://localhost:4501/enderecos/3
Content-Type: application/json

{
    "id_uf_fk": 25,
    "id_cidade_fk": 2,
    "id_bairro_fk": 13,
    "id_rua_fk": 1,
    "numero": 1690,
    "cep": 15997070
}