### Lista espécies
GET http://localhost:4501/especies

### Encontra espécie pelo ID
GET http://localhost:4501/especies/4

### Adicionar espécie
POST http://localhost:4501/especies
Content-Type: application/json

{
    "especie": "Rato"
}

### Deleta espécie pelo ID
DELETE http://localhost:4501/especies/4

### Altera espécie pelo ID
PUT http://localhost:4501/especies/4
Content-Type: application/json

{
    "especie": "Jaca"
}