### Lista as ONGs
GET http://localhost:4501/ongs

### Encontra Ong pelo ID
GET http://localhost:4501/ongs/32

### Criar nova ONG
POST http://localhost:4501/ongs/criar-ong
Content-Type: application/json
{
  "nome_responsavel": "Ana Maria",
  "email": "anamaria@exemplo.com",
  "telefone": "1633330000",
  "celular": "16999999999",
  "senha": "senhaSegura123",
  "foto": "ana.jpg",
  "nome_ong": "Patas Unidas",
  "cnpj": "12.345.678/0001-90",
  "banner": "banner_ong.jpg",
  "descricao": "ONG dedicada ao resgate de animais em situação de risco."
}

### Atualizar nome da ONG
PUT http://localhost:4501/ongs/atualizar-nome-ong/32
Content-Type: application/json

{
  "nome_ong": "ONG Patinhas"
}

### Deletar ONG
DELETE http://localhost:4501/ongs/33
