### Lista responsáveis

GET http://localhost:4501/responsaveis

### Encontra responsavel pelo ID

GET http://localhost:4501/responsaveis/3

### Adicionar responsavel
POST http://localhost:4501/responsaveis
Content-Type: application/json

{
    "nome_responsavel": "Maria",
    "id_ong_fk": 22,
    "cpf_responsavel": 44444444444,
    "email_responsavel": "maria@gmail.com"
}

### Deleta responsavel pelo ID

DELETE http://localhost:4501/responsaveis/3

### Altera responsavel pelo ID

PUT http://localhost:4501/responsaveis/3
Content-Type: application/json

{
    "nome_responsavel": "Maria Fernanda",
    "id_ong_fk": 22,
    "cpf_responsavel": 33333333333,
    "email_responsavel": "mariafer@gmail.com"
}