### Lista sexos
GET http://localhost:4501/sexopets

### Encontra sexo pelo ID
GET http://localhost:4501/sexopets/5

### Adicionar sexo
POST http://localhost:4501/sexopets
Content-Type: application/json

{
  "sexo_pet": "es"
}

### Deleta sexo pelo ID
DELETE http://localhost:4501/sexopets/5

### Altera sexo pelo ID
PUT http://localhost:4501/sexopets/5
Content-Type: application/json

{
  "sexo_pet": "ovo"
}
